pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Architectury'
			url = 'https://maven.architectury.dev/'
		}
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid / archives base name
rootProject.name = 'cobble_mounts'
